- hosts: all
  become: true
  tasks:
    - name: Install Java
      yum:
        name: java-11-amazon-corretto-devel
        state: present
    - name: add tomcatuser
      user:
        name: tomcat
        shell: /sbin/nologin
    - name: Tomcat-9 Installation
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz
        dest: /tmp/
    - name: copy
      copy:
        src: /tmp/apache-tomcat-9.0.80.tar.gz
        dest: /usr/local/
        remote_src: yes
    - name: Unpacking the archive
      unarchive:
        src: /usr/local/apache-tomcat-9.0.80.tar.gz
        dest: /usr/local
        remote_src: yes
    - name: Change file ownership, group and permissions
      file:
        path: /usr/local/apache-tomcat-9.0.80
        owner: tomcat
        group: tomcat
        recurse: yes
        state: directory
    - name: make tomcat symbolic link
      file:
        src: /usr/local/apache-tomcat-9.0.80
        dest: /usr/local/tomcat9
        owner: tomcat
        group: tomcat
        state: link
    - name: make tomcat.service
      file:
        path: /etc/systemd/system/tomcat.service
        state:  touch
    - name: edit tomcat.service
      blockinfile:
        dest: /etc/systemd/system/tomcat.service
        insertafter:
        block: |
          [Unit]
          Description = Apache Tomcat 9
          After = syslog.target network.target
          [Service]
          User = tomcat
          Group = tomcat
          Type = oneshot
          PIDFile =/usr/local/apache-tomcat-9.0.80/tomcat.pid
          RemainAfterExit = yes
          ExecStart =/usr/local/apache-tomcat-9.0.80/bin/startup.sh
          ExecStop =/usr/local/apache-tomcat-9.0.80/bin/shutdown.sh
          ExecReStart =/usr/local/apache-tomcat-9.0.80/bin/shutdown.sh;/usr/local/apache-tomcat-9.0.80/bin/startup.sh
          [Install]
          WantedBy = multi-user.target
    - name: chmod 755 tomcat.service
      file:
        path: /etc/systemd/system/tomcat.service
        mode:  0755
    - name: start tomcat
      systemd:
        name: tomcat.service
        state: started
        daemon_reload: yes
        enabled: yes
